name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Cross-Compile for amd64
      run: |
        cd container/go
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-X main.Revision=a" -o app-amd64

    - name: Cross-Compile for arm64
      run: |
        cd container/go
        CGO_ENABLED=0  GOOS=linux GOARCH=arm64 go build -ldflags "-X main.Revision=${{ github.sha }}" -o app-arm64

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}


    - name: Build for amd64
      uses: docker/build-push-action@v6
      with:
        context: container/go
        target: ci
        tags: |
          ghcr.io/${{ github.repository }}:amd64
        platforms: linux/amd64
        push: true
        build-args: |
          BIN=app-amd64
          REVISION=${{github.sha}}

    - name: Build for arm64
      uses: docker/build-push-action@v6
      with:
        context: container/go
        target: ci
        tags: |
          ghcr.io/${{ github.repository }}:arm64
        platforms: linux/arm64
        push: true
        build-args: |
          BIN=app-arm64
          REVISION=${{github.sha}}

    - name: Push Multi-Arch Manifest
      run: |
        docker manifest create ghcr.io/${{ github.repository }} \
          ghcr.io/${{ github.repository }}:amd64 \
          ghcr.io/${{ github.repository }}:arm64
        docker manifest push ghcr.io/${{ github.repository }}
